### ISSUE TITLE
Onscreen keyboard doesn't show up when selecting 'Start ZShaolin'

### ISSUE THREAD

**Issue by mikepjb** [dyne/ZShaolin#3]
A workaround to this is to press the back button, returning to the original screen and select 'Start ZShaolin' for a second time

This happens on my HTC mini 2 and using the version from the Google Play store not I'm not sure whether this issue is outdated.

**Comment by jaromil** [comment]
I guess is related to this https://bugs.dyne.org/view.php?id=381 which is reported on the old bugtracker. Thanks for noting this down here, Github issues are the current way to report.
